### ISSUE TITLE
Move to Los Angeles permanently

### ISSUE THREAD

**Issue by MordoJ** [dil-classroom/projet-dil-diep_jean_rodr_stocc#54]
This is clearly the best things to do.

**Comment by danpa32** [comment]
Steps to accomplish before the Great Journey to LA:
1. Finish the project => leads to cries of despair or tears of joy
3. Might help: https://www.google.com/search?client=firefox-b-d&q=Move+to+Los+Angeles+permanently
4. Farewell party

Send pics when you get there ;-)

**Comment by MordoJ** [comment]
Thank you so much, now I’m finally ready to move to Los Angeles (permanently, obvi). It’s only thanks to you!
However there is one matter I’d like to discuss with you:
Accordingly to your response, the first step is to finish the project, can you elaborate more on that please? Because it doesn’t make sense to me at all. I’d even say that it’s the whole point of moving to California.
